// Code generated by MockGen. DO NOT EDIT.
// Source: repositories/item_repository.go

// Package repositories is a generated GoMock package.
package repositories

import (
	models "gin-freemarket/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIItemRepository is a mock of IItemRepository interface.
type MockIItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIItemRepositoryMockRecorder
}

// MockIItemRepositoryMockRecorder is the mock recorder for MockIItemRepository.
type MockIItemRepositoryMockRecorder struct {
	mock *MockIItemRepository
}

// NewMockIItemRepository creates a new mock instance.
func NewMockIItemRepository(ctrl *gomock.Controller) *MockIItemRepository {
	mock := &MockIItemRepository{ctrl: ctrl}
	mock.recorder = &MockIItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIItemRepository) EXPECT() *MockIItemRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIItemRepository) Create(newItem models.Item) (*models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", newItem)
	ret0, _ := ret[0].(*models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIItemRepositoryMockRecorder) Create(newItem interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIItemRepository)(nil).Create), newItem)
}

// Delete mocks base method.
func (m *MockIItemRepository) Delete(itemId, userId uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", itemId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIItemRepositoryMockRecorder) Delete(itemId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIItemRepository)(nil).Delete), itemId, userId)
}

// FindAll mocks base method.
func (m *MockIItemRepository) FindAll() (*[]models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].(*[]models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIItemRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIItemRepository)(nil).FindAll))
}

// FindById mocks base method.
func (m *MockIItemRepository) FindById(itemId, userId uint) (*models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", itemId, userId)
	ret0, _ := ret[0].(*models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockIItemRepositoryMockRecorder) FindById(itemId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockIItemRepository)(nil).FindById), itemId, userId)
}

// Update mocks base method.
func (m *MockIItemRepository) Update(newItem models.Item) (*models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", newItem)
	ret0, _ := ret[0].(*models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIItemRepositoryMockRecorder) Update(newItem interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIItemRepository)(nil).Update), newItem)
}
